import requests
import base64
from datetime import datetime
import os

# -------------------------------------------------------------
# Helper: Commit file to GitHub and open PR
# -------------------------------------------------------------
def commit_to_github(
    repo_url: str,
    token: str,
    base_branch: str,
    new_branch: str,
    file_path: str,
    commit_message: str
):
    """
    Commits a file to GitHub by:
    1. Creating a new branch (timestamped)
    2. Uploading the file
    3. Opening a Pull Request into base_branch

    Returns: (ok, message)
    """

    try:
        if not repo_url or not token:
            return False, "Missing repo URL or token"

        # Extract repo owner/name from URL
        repo_url = repo_url.strip().rstrip(".git").replace("https://github.com/", "")
        api_base = f"https://api.github.com/repos/{repo_url}"

        headers = {
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github+json"
        }

        # Step 1: Get base branch SHA
        r = requests.get(f"{api_base}/git/ref/heads/{base_branch}", headers=headers)
        if r.status_code != 200:
            return False, f"Base branch not found: {r.text}"
        base_sha = r.json()["object"]["sha"]

        # Step 2: Create new branch (with timestamp to prevent duplicates)
        unique_branch = f"{new_branch}-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        ref_data = {"ref": f"refs/heads/{unique_branch}", "sha": base_sha}
        r = requests.post(f"{api_base}/git/refs", headers=headers, json=ref_data)
        if r.status_code not in [200, 201]:
            return False, f"Failed to create branch: {r.text}"

        # Step 3: Read file content and encode
        if not os.path.exists(file_path):
            return False, f"File not found: {file_path}"
        with open(file_path, "rb") as f:
            content = f.read()
        encoded = base64.b64encode(content).decode("utf-8")

        # Step 4: Create/update the file on the branch
        filename = os.path.basename(file_path)
        file_api = f"{api_base}/contents/{file_path}"

        data = {
            "message": commit_message,
            "content": encoded,
            "branch": unique_branch
        }

        r = requests.put(file_api, headers=headers, json=data)
        if r.status_code not in [200, 201]:
            return False, f"Failed to update file: {r.text}"

        # Step 5: Create PR into base branch
        pr_title = f"Automated update: {filename} ({datetime.now().strftime('%Y-%m-%d %H:%M:%S')})"
        pr_body = (
            f"This PR was automatically generated by BactAI-D Training.\n"
            f"File updated: `{file_path}`\n\n"
            f"Commit message:\n```\n{commit_message}\n```"
        )
        pr_data = {
            "title": pr_title,
            "body": pr_body,
            "head": unique_branch,
            "base": base_branch
        }

        r = requests.post(f"{api_base}/pulls", headers=headers, json=pr_data)
        if r.status_code not in [200, 201]:
            return False, f"Open PR failed: {r.text}"

        pr_url = r.json().get("html_url", "")
        return True, f"✅ PR created successfully: {pr_url}"

    except Exception as e:
        return False, f"GitHub commit exception: {e}"
